services:
  rss-sponsorblock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss-sponsorblock
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    env_file: .env
    environment:
      - SERVER_HOST=0.0.0.0
      - STORAGE_DIR=/app/storage
    volumes:
      - ./storage:/app/storage
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  storage: